name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: poetry install --sync

      - name: Lint with flake8
        run: make lint

      - name: Test with pytest
        run: make test

      - name: Run tests with coverage
        run: poetry run pytest --cov=gendiff --cov-report=xml

      - name: Upload coverage to CodeClimate
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.xml
