name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install "poetry<2.0"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint with flake8
        run: make lint

      - name: Run tests with coverage
        run: poetry run pytest --cov=gendiff --cov-report=xml:coverage.xml --cov-report=term-missing

      - name: Check coverage.xml content
        run: |
          ls -lh coverage.xml
          head -n 20 coverage.xml

      - name: Upload coverage to Qlty.sh
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.xml

