name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry 1.7.x
        run: pip install "poetry<2.0"
      
      - name: Install dependencies
        run: |
          poetry install --with dev
          poetry run pip install flake8 coverage coverage-lcov

      - name: Lint with flake8
        run: make lint

      - name: Test with pytest
        run: make test

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          poetry run pytest --cov=gendiff --cov-report xml:coverage.xml
          poetry run coverage-lcov --xml-file coverage.xml --lcov-file reports/lcov.info

      - name: Upload coverage to CodeClimate
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info
